### ISSUE TITLE
Remember?

### ISSUE THREAD

**Issue by ClashLuke** [ClashLuke/Dune-Clone#1]
@blenderfreaky

**Comment by kilyanni** [comment]
@Yes

**Comment by ClashLuke** [comment]
Why the fuck did you ping this random dude

**Comment by ClashLuke** [comment]
Wenn du das level design okay findest, brauchen wir jetzt noch physics.
Collisionen würde ich über pixelfarbe machen, meine beta version ist ja sichtbar.
